CREATE TABLE config (
    guild_id BIGINT PRIMARY KEY NOT NULL,
    member_role BIGINT DEFAULT 0,
    stateless_role BIGINT DEFAULT 0,
    welcome_channel BIGINT DEFAULT 0,
    journalism_channel BIGINT DEFAULT 0
);

CREATE TABLE nations (
    nation_id VARCHAR(50) PRIMARY KEY NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    description VARCHAR(500) DEFAULT "No description." NOT NULL,
    role_id BIGINT DEFAULT 0
    join_condition TINYINT DEFAULT 1,
    invite_permission TINYINT DEFAULT 0,
    claim_time BIGINT DEFAULT 0,
    tux_balance BIGINT DEFAULT 0,
    government_type TINYINT DEFAULT 0,
    ideology TINYINT DEFAULT 8,
    leadership_changes BIGINT DEFAULT 0,
    last_leadership_change BIGINT DEFAULT 0,
    government_changes BIGINT DEFAULT 0,
    last_government_change BIGINT DEFAULT 0,
    media_freedom TINYINT DEFAULT 100,
    media_posts BIGINT DEFAULT 0,
    last_post BIGINT DEFAULT 0,
    censored_posts BIGINT DEFAULT 0,
    media_whitelist BOOLEAN DEFAULT 0,
    media_blacklist BOOLEAN DEFAULT 0,
    last_manual_censorship BIGINT DEFAULT 0,
    last_automatic_censorship BIGINT DEFAULT 0,
    nuclear_state TINYINT DEFAULT 0,
    acquired_nuclear_time BIGINT DEFAULT 0,
    veto_state BOOLEAN DEFAULT 0,
    veto_usage_count BIGINT DEFAULT 0,
    last_veto_usage BIGINT DEFAULT 0,
    resolutions_count BIGINT DEFAULT 0,
    last_resolution BIGINT DEFAULT 0,
    passed_resolutions BIGINT DEFAULT 0,
    last_passed_resolution BIGINT DEFAULT 0
);

CREATE TABLE nationality (
    user_id BIGINT PRIMARY KEY NOT NULL,
    nation_id VARCHAR(30) DEFAULT 0,
    rank TINYINT DEFAULT 0,
    last_rank_update BIGINT DEFAULT 0,
    joining_time BIGINT DEFAULT 0
);

CREATE TABLE relations (
    defining_nation VARCHAR(30) NOT NULL,
    targeted_nation VARCHAR(30) NOT NULL,
    relation_score TINYINT DEFAULT 50,
    PRIMARY KEY (defining_nation, targeted_nation)
);

CREATE TABLE sanctions (
    resolution_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    pending BOOLEAN DEFAULT TRUE,
    nation_id VARCHAR(30) NOT NULL,
    sanctioned_nation VARCHAR(30) NOT NULL,
    sanction_type TINYINT,
    sanction_title VARCHAR(100) NOT NULL,
    sanction_details VARCHAR(500) NOT NULL,
    sanction_amount BIGINT NOT NULL,
    sanction_start BIGINT NOT NULL,
    sanction_duration VARCHAR(3) NOT NULL,
    sanction_end BIGINT NOT NULL,
    vote_start BIGINT DEFAULT (UNIX_TIMESTAMP()) NOT NULL,
    vote_duration VARCHAR(3) NOT NULL,
    vote_end BIGINT NOT NULL,
    votes_for TEXT DEFAULT "",
    votes_against TEXT DEFAULT ""
);

CREATE TABLE laws (
    resolution_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    pending BOOLEAN DEFAULT TRUE,
    nation_id VARCHAR(30) NOT NULL,
    law_title VARCHAR(100) NOT NULL,
    law_details VARCHAR(500) NOT NULL,
    law_adoption_time BIGINT DEFAULT 0,
    vote_start BIGINT DEFAULT (UNIX_TIMESTAMP()) NOT NULL,
    vote_duration VARCHAR(3) NOT NULL,
    vote_end BIGINT NOT NULL,
    votes_for TEXT DEFAULT "",
    votes_against TEXT DEFAULT ""
);

CREATE TABLE un_membership (
    nation_id VARCHAR(30) PRIMARY KEY NOT NULL,
    pending BOOLEAN DEFAULT TRUE,
    invited_by VARCHAR(30) NOT NULL,
    joining_time BIGINT DEFAULT 0,
    vote_start BIGINT DEFAULT (UNIX_TIMESTAMP()) NOT NULL,
    vote_duration VARCHAR(3) NOT NULL,
    vote_end BIGINT NOT NULL,
    votes_for TEXT DEFAULT "",
    votes_against TEXT DEFAULT ""
);

CREATE TABLE journalism (
    user_id BIGINT PRIMARY KEY NOT NULL,
    status TINYINT
);



INSERT INTO nations (nation_id, display_name) VALUES
("afghanistan", "Afghanistan"),
("albania", "Albania"),
("algeria", "Algeria"),
("andorra", "Andorra"),
("angola", "Angola"),
("antigua_and_barbuda", "Antigua and Barbuda"),
("argentina", "Argentina"),
("armenia", "Armenia"),
("australia", "Australia"),
("austria", "Austria"),
("azerbaijan", "Azerbaijan"),
("bahamas", "Bahamas"),
("bahrain", "Bahrain"),
("bangladesh", "Bangladesh"),
("barbados", "Barbados"),
("belarus", "Belarus"),
("belgium", "Belgium"),
("belize", "Belize"),
("benin", "Benin"),
("bhutan", "Bhutan"),
("bolivia", "Bolivia"),
("bosnia_and_herzegovina", "Bosnia and Herzegovina"),
("botswana", "Botswana"),
("brazil", "Brazil"),
("brunei", "Brunei"),
("bulgaria", "Bulgaria"),
("burkina_faso", "Burkina Faso"),
("burundi", "Burundi"),
("cabo_verde", "Cabo Verde"),
("cambodia", "Cambodia"),
("cameroon", "Cameroon"),
("canada", "Canada"),
("central_african_republic", "Central African Republic"),
("chad", "Chad"),
("chile", "Chile"),
("china", "China"),
("colombia", "Colombia"),
("comoros", "Comoros"),
("congo_brazzaville", "Republic of the Congo"),
("costa_rica", "Costa Rica"),
("cote_divoire", "Côte d'Ivoire"),
("croatia", "Croatia"),
("cuba", "Cuba"),
("cyprus", "Cyprus"),
("czechia", "Czech Republic"),
("denmark", "Denmark"),
("djibouti", "Djibouti"),
("dominica", "Dominica"),
("dominican_republic", "Dominican Republic"),
("dr_congo", "Democratic Republic of the Congo"),
("ecuador", "Ecuador"),
("egypt", "Egypt"),
("el_salvador", "El Salvador"),
("equatorial_guinea", "Equatorial Guinea"),
("eritrea", "Eritrea"),
("estonia", "Estonia"),
("eswatini", "Eswatini"),
("ethiopia", "Ethiopia"),
("fiji", "Fiji"),
("finland", "Finland"),
("france", "France"),
("gabon", "Gabon"),
("gambia", "Gambia"),
("georgia", "Georgia"),
("germany", "Germany"),
("ghana", "Ghana"),
("greece", "Greece"),
("grenada", "Grenada"),
("guatemala", "Guatemala"),
("guinea", "Guinea"),
("guinea_bissau", "Guinea-Bissau"),
("guyana", "Guyana"),
("haiti", "Haiti"),
("honduras", "Honduras"),
("hungary", "Hungary"),
("iceland", "Iceland"),
("india", "India"),
("indonesia", "Indonesia"),
("iran", "Iran"),
("iraq", "Iraq"),
("ireland", "Ireland"),
("israel", "Israel"),
("italy", "Italy"),
("jamaica", "Jamaica"),
("japan", "Japan"),
("jordan", "Jordan"),
("kazakhstan", "Kazakhstan"),
("kenya", "Kenya"),
("kiribati", "Kiribati"),
("kuwait", "Kuwait"),
("kyrgyzstan", "Kyrgyzstan"),
("laos", "Laos"),
("latvia", "Latvia"),
("lebanon", "Lebanon"),
("lesotho", "Lesotho"),
("liberia", "Liberia"),
("libya", "Libya"),
("liechtenstein", "Liechtenstein"),
("lithuania", "Lithuania"),
("luxembourg", "Luxembourg"),
("madagascar", "Madagascar"),
("malawi", "Malawi"),
("malaysia", "Malaysia"),
("maldives", "Maldives"),
("mali", "Mali"),
("malta", "Malta"),
("marshall_islands", "Marshall Islands"),
("mauritania", "Mauritania"),
("mauritius", "Mauritius"),
("mexico", "Mexico"),
("micronesia", "Federated States of Micronesia"),
("moldova", "Moldova"),
("monaco", "Monaco"),
("mongolia", "Mongolia"),
("montenegro", "Montenegro"),
("morocco", "Morocco"),
("mozambique", "Mozambique"),
("myanmar", "Myanmar"),
("namibia", "Namibia"),
("nauru", "Nauru"),
("nepal", "Nepal"),
("netherlands", "Netherlands"),
("new_zealand", "New Zealand"),
("nicaragua", "Nicaragua"),
("niger", "Niger"),
("nigeria", "Nigeria"),
("north_korea", "North Korea"),
("north_macedonia", "North Macedonia"),
("norway", "Norway"),
("oman", "Oman"),
("pakistan", "Pakistan"),
("palau", "Palau"),
("panama", "Panama"),
("papua_new_guinea", "Papua New Guinea"),
("paraguay", "Paraguay"),
("peru", "Peru"),
("philippines", "Philippines"),
("poland", "Poland"),
("portugal", "Portugal"),
("qatar", "Qatar"),
("romania", "Romania"),
("russia", "Russia"),
("rwanda", "Rwanda"),
("saint_kitts_and_nevis", "Saint Kitts and Nevis"),
("saint_lucia", "Saint Lucia"),
("saint_vincent_and_the_grenadines", "Saint Vincent and the Grenadines"),
("samoa", "Samoa"),
("san_marino", "San Marino"),
("sao_tome_and_principe", "São Tomé and Príncipe"),
("saudi_arabia", "Saudi Arabia"),
("senegal", "Senegal"),
("serbia", "Serbia"),
("seychelles", "Seychelles"),
("sierra_leone", "Sierra Leone"),
("singapore", "Singapore"),
("slovakia", "Slovakia"),
("slovenia", "Slovenia"),
("solomon_islands", "Solomon Islands"),
("somalia", "Somalia"),
("south_africa", "South Africa"),
("south_korea", "South Korea"),
("south_sudan", "South Sudan"),
("spain", "Spain"),
("sri_lanka", "Sri Lanka"),
("st_lucia", "Saint Lucia"),
("sudan", "Sudan"),
("suriname", "Suriname"),
("sweden", "Sweden"),
("switzerland", "Switzerland"),
("syria", "Syria"),
("tajikistan", "Tajikistan"),
("tanzania", "Tanzania"),
("thailand", "Thailand"),
("timor_leste", "Timor-Leste"),
("togo", "Togo"),
("tonga", "Tonga"),
("trinidad_and_tobago", "Trinidad and Tobago"),
("tunisia", "Tunisia"),
("turkey", "Turkey"),
("turkmenistan", "Turkmenistan"),
("tuvalu", "Tuvalu"),
("uganda", "Uganda"),
("ukraine", "Ukraine"),
("uae", "United Arab Emirates"),
("uk", "United Kingdom"),
("usa", "United States"),
("uruguay", "Uruguay"),
("uzbekistan", "Uzbekistan"),
("vanuatu", "Vanuatu"),
("vatican_city", "Vatican City"),
("venezuela", "Venezuela"),
("vietnam", "Vietnam"),
("yemen", "Yemen"),
("zambia", "Zambia"),
("zimbabwe", "Zimbabwe");
